name: aarch64

on: [push, pull_request]

env:
  BOINC_DIR: ./boinc

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    name: linux aarch / ubuntu

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install gcc
        run: |
          sudo apt-get install gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          sudo update-alternatives --config gcc
          sudo update-alternatives --config g++

      - name: Print GCC version
        run: |
          gcc -v

      - name: Install opencl
        run: |
          sudo apt-get install opencl-headers ocl-icd-opencl-dev

      - name: Build BOINC
        run: |
          cd ..
          git clone --depth 1 https://github.com/BOINC/boinc.git
          cd boinc
          ./_autosetup
          ./configure --host=aarch64-linux --with-boinc-platform="aarch64-unknown-linux-gnu" --disable-server --disable-manager --disable-client --enable-static CXXFLAGS="-O3"
          make -j

      - name: Build project
        working-directory: ./genefer
        run: |
          make -f makefile_linux_arm -j

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linuxaarch64-latest
          retention-days: 1
          path: ./bin/*