name: x64

on: [push, pull_request]

env:
  BOINC_DIR: ./boinc

jobs:
  build:
    runs-on: ubuntu-latest
    name: windows64 / ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install libraries
        run: |
          sudo apt-get install opencl-headers ocl-icd-opencl-dev libgmp-dev

      - name: Download gcc
        run: |
          mkdir -p $HOME/winlibs
          wget -q https://github.com/brechtsanders/winlibs_mingw/releases/download/15.1.0posix-12.0.0-msvcrt-r1/winlibs-x86_64-posix-seh-gcc-15.1.0-mingw-w64msvcrt-12.0.0-r1.7z
          7z x winlibs-x86_64-posix-seh-gcc-15.1.0-mingw-w64msvcrt-12.0.0-r1.7z -o$HOME/winlibs

      - name: Print GCC version
        run: |
          export PATH="$HOME/winlibs/mingw64/bin:$PATH"
          gcc -v

      - name: Build OpenCL.dll
        run: |
          export PATH="$HOME/winlibs/mingw64/bin:$PATH"
          git clone --depth 1 https://github.com/KhronosGroup/OpenCL-ICD-Loader
          git clone --depth 1 https://github.com/KhronosGroup/OpenCL-Headers
          cd OpenCL-ICD-Loader
          mkdir build-mingw
          cd build-mingw
          cmake .. -DCMAKE_SYSTEM_NAME=Windows -DOPENCL_ICD_LOADER_HEADERS_DIR=../../OpenCL-Headers -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./install
          make -j
          make install

      - name: Build BOINC
        run: |
          export PATH="$HOME/winlibs/mingw64/bin:$PATH"
          cd ..
          git clone --depth 1 https://github.com/BOINC/boinc.git
          cd boinc
          ./_autosetup
          ./configure --host=x86_64-w64-mingw32 --with-boinc-platform="windows_x86_64" --disable-server --disable-manager --disable-client --enable-static CXXFLAGS="-O3"
          make -j

      - name: Build GMP
        run: |
          export PATH="$HOME/winlibs/mingw64/bin:$PATH"
          git clone --depth 1 https://github.com/gmp-mirror/gmp-6.3.git
          cd gmp-6.3
          ./.bootstrap
          ./configure --host=x86_64-w64-mingw32 --prefix=${GITHUB_WORKSPACE}/../gmp
          make -j
          make install

      - name: Build project
        working-directory: ./genefer
        run: |
          export PATH="$HOME/winlibs/mingw64/bin:$PATH"
          make -f Makefile_win64 -j OCL_LIB=/home/runner/work/genefer22/genefer22/OpenCL-ICD-Loader/build-mingw/install/lib/libOpenCL.dll.a

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows64-latest
          retention-days: 1
          path: ./bin/*